spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf6segs9b0026tny3ho.mysql.rds.aliyuncs.com:3306/cw_market_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: cw_market_user
    password: "uDEc3&P8KiKS_BL"
  sql:
    init:
      mode: always

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
