server:
  port: 18818
  servlet:
    context-path: /cw
spring:
  datasource:
    dynamic:
      primary: market
      strict: false
      datasource:
        market:
          url: jdbc:mysql://rm-uf6segs9b0026tny3ho.mysql.rds.aliyuncs.com:3306/cw_market_data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: cw_market_read
          password: "&r_S4G8K#4+!i7H"
          driver-class-name: com.mysql.cj.jdbc.Driver
        trade:
          url: jdbc:mysql://rm-uf6segs9b0026tny3ho.mysql.rds.aliyuncs.com:3306/cw_backtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: cw_backtest_user
          password: "@9nhJ%Urx%kUeA9"
          driver-class-name: com.mysql.cj.jdbc.Driver
        clickhouse:
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
          url: jdbc:clickhouse:http://backtest.base32.cn:8123/stock?ignore_unknown_config_key=true&jdbc_ignore_unsupported_values=true
          username: lv2data13
          password: "hisdata@N90L"

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
